from .identity import *
from .customer import *
from .parcels import *
from .deliveries import *
from .availability import *
from .predefined_fake_data import *
from .vehicles import *
from .fake_collection import *
from .settings import *
